### ISSUE TITLE
Rake tasks failing upon inclusion into Gemfile

### ISSUE THREAD

**Issue by storm255** [gregory/jouba#2]
Hi.

Not sure if this is related to the recent refactoring but rake is failing when Jouba is included in my Gemfile.  Have the requirements changed?

Mark.

rake aborted!
LoadError: cannot load such file -- pry
/home/mark/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jouba-1.0.1/lib/jouba.rb:1:in `require'
/home/mark/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/jouba-1.0.1/lib/jouba.rb:1:in`<top (required)>'
/home/mark/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundler/runtime.rb:76:in `require'
/home/mark/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundler/runtime.rb:76:in`block (2 levels) in require'
/home/mark/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundler/runtime.rb:72:in `each'
/home/mark/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundler/runtime.rb:72:in`block in require'
/home/mark/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundler/runtime.rb:61:in `each'
/home/mark/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundler/runtime.rb:61:in`require'
/home/mark/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.6.5/lib/bundler.rb:132:in `require'
/home/mark/RubymineProjects/beau/config/application.rb:15:in`<top (required)>'
/home/mark/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/mark/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
/home/mark/RubymineProjects/beau/Rakefile:4:in `<top (required)>'
/home/mark/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in`load'
/home/mark/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/home/mark/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:689:in`raw_load_rakefile'
/home/mark/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'
/home/mark/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in`standard_exception_handling'
/home/mark/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
/home/mark/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:77:in`block in run'
/home/mark/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/mark/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in`run'
/home/mark/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/mark/.rbenv/versions/2.1.2/bin/rake:23:in`load'
/home/mark/.rbenv/versions/2.1.2/bin/rake:23:in `<main>'

**Comment by gregory** [comment]
Hey @storm255  i'll check that out tonight and keep you up! Thx for reporting

**Comment by storm255** [comment]
Thanks gregory.  It seems just removing the require for pry in lib/jouba.rb allowed startup after I managed to track down a problem with the underlying macaddr gem on my machine.  I have a few openvpn tun devices active that it was struggling with and it needed the ifconfig command available as well (archlinux is using ip address show).

Hoping to work through this now :)

**Comment by gregory** [comment]
cool, could you open PR please ? - removing the require pry sounds like the fix.

**Comment by gregory** [comment]
i just [bumped](https://github.com/gregory/jouba/commit/3faeba559a7dada52e1f9927d827524a131acc31), should be fixed.
